logging:
  level:
    com.github.schaka: INFO
  threshold:
    file: NONE

file-system:
  access: false
  validate-seeding: true
  leaving-soon-dir: "/data/media/leaving-soon"
  media-server-leaving-soon-dir: "/data/media/leaving-soon"
  from-scratch: true
  free-space-check-dir: "/"

application:
  dry-run: false
  run-once: false
  whole-tv-show: false
  whole-show-seeding-check: false
  leaving-soon: 14d
  exclusion-tag: "janitorr_keep"

  media-deletion:
    enabled: false
    movie-expiration:
      5: 15d # 15 days
      10: 30d # 1 month - if a movie's files on your system are older than this, they will be deleted
      15: 30d # 2 months
      20: 90d # 3 months
    season-expiration:
      5: 15d # 15 days
      10: 20d # 20 days - if a season's files on your system are older than this, they will be deleted
      15: 60d # 2 months
      20: 120d # 4 months

  tag-based-deletion:
    enabled: false
    minimum-free-disk-percent: 100
    schedules:
      - tag: 5 - demo
        expiration: 30d
      - tag: 10 - demo
        expiration: 7d

  episode-deletion:
    enabled: false
    tag: janitorr_daily
    max-episodes: 10
    max-age: 30d


clients:
  sonarr:
    enabled: false
    url: "http://localhost:8989"
    api-key: "4ed7f4d0e8584d65aa2d47d944077ff6"
    delete-empty-shows: true
    determine-age-by: MOST_RECENT
  radarr:
    enabled: false
    url: "http://localhost:7878"
    api-key: "cd0912f129d348c9b69bb20d49fcbe44"
    only-delete-files: false
    determine-age-by: most_recent
  bazarr:
    enabled: false
    url: "http://localhost:6767"
    api-key: "cd0912f129d348c9b69bb20d49fcbe55"

  jellyfin:
    enabled: false
    url: "http://localhost:8096"
    api-key: "4da8d93992804489ba2d1f0e31b8316c"
    username: Janitorr
    password: janitorr
    delete: true
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
    leaving-soon-type: MOVIES_AND_TV

  emby:
    enabled: false
    url: "http://localhost:8096"
    api-key: "4da8d93992804489ba2d1f0e31b8316c"
    username: Janitorr
    password: janitorr
    delete: true
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
    leaving-soon-type: MOVIES_AND_TV

  jellyseerr:
    enabled: false
    url: "http://localhost:5055"
    api-key: "MTY3NzU3NzI0NzgzOWFhNWYxMGE4LWNlMWYtNDc1ZS04ODYzLThkMjQyMTQ4M2NiZCe="
    match-server: false

  jellystat:
    enabled: false
    whole-tv-show: false
    url: "http://jellystat:3000"
    api-key: "jellystat-key"

  streamystats:
    enabled: false
    whole-tv-show: false
    url: "http://streamystats:3000"
    username: Janitorr
    password: janitorr