api = "0.9"

[buildpack]
id = "schaka/aot-cache"
version = "0.0.1"
name = "AOT Cache Copy Buildpack"

[[stacks]]
id = "io.buildpacks.stacks.noble"

[metadata]
requires = ["jre"]
provides = ["aot-cache"]