package com.github.schaka.janitorr.servarr.sonarr.series

import com.github.schaka.janitorr.servarr.data_structures.Image

data class SeriesPayload(
        val added: String,
        val airTime: String?,
        val alternateTitles: List<AlternateTitle>,
        val certification: String?,
        val cleanTitle: String,
        val ended: Boolean,
        val firstAired: String?,
        val genres: List<String>,
        val id: Int,
        val images: List<Image>,
        val imdbId: String?,
        val languageProfileId: Int,
        val lastAired: String?,
        val monitored: Boolean,
        val network: String?,
        val nextAiring: String?,
        val originalLanguage: OriginalLanguage,
        val overview: String,
        val path: String,
        val previousAiring: String?,
        val qualityProfileId: Int,
        val ratings: Ratings,
        val rootFolderPath: String,
        val runtime: Int,
        val seasonFolder: Boolean,
        val seasons: List<Season>,
        val seriesType: String,
        val sortTitle: String,
        val statistics: StatisticsX,
        val status: String,
        val tags: List<Any>,
        val title: String,
        val titleSlug: String,
        val tvMazeId: Int,
        val tvRageId: Int,
        val tvdbId: Int,
        val useSceneNumbering: Boolean,
        val year: Int
)