name: Combine native images

on:
  workflow_run:
    workflows: [ "Native x86 image", "Native aarch64 image" ]  # Must match the name of the first workflow
    types: [ completed ]    # Runs when the workflow finishes

jobs:
  combine-images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only if build succeeded

    steps:
      - name: Export branch name
        uses: mad9000/actions-find-and-replace-string@5
        id: branch_name
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - name: Combine native images into single manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          push: true
          tags: |
            ghcr.io/schaka/janitorr:native-${{ steps.branch_name.outputs.value }}
            ${{ (startsWith(github.ref, 'refs/tags/v') && 'ghcr.io/schaka/janitorr:native-stable') || '' }}
          sources: |
            ghcr.io/schaka/janitorr:native-amd64-${{ steps.branch_name.outputs.value }}
            ghcr.io/schaka/janitorr:native-arm64-${{ steps.branch_name.outputs.value }}
          
