name: JVM Image

on:
  push:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
    tags:
      - '**'
    branches:
      - 'develop'

  pull_request:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
    branches:
      - '**'

jobs:
  build-jvm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Log in to Docker Hub to pull images without rate limit
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0

      - name: Build JVM OCI image
        run: ./gradlew jib -Djib.serialize=true # https://github.com/GoogleContainerTools/jib/issues/4301
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          
