name: Native images

on:
  push:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
    tags:
      - '**'
    branches:
      - 'develop'

  pull_request:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
    branches:
      - '**'

jobs:
  build-native-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub to pull images without rate limit
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.2

      - name: Build Native OCI Image
        run: ./gradlew bootBuildImage --publishImage --imagePlatform linux/amd64
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          TARGET_PLATFORM: "amd64"

  build-native-aarch64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.2

      - name: Build Native ARM64 OCI Image
        run: ./gradlew bootBuildImage --publishImage --imagePlatform linux/arm64
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          TARGET_PLATFORM: "arm64"

  combine-images:
    runs-on: ubuntu-latest
    needs: [build-native-x86, build-native-aarch64]
    steps:
      - name: Export branch name
        uses: mad9000/actions-find-and-replace-string@5
        id: branch_name
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - name: Combine native images into single manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          push: true
          tags: |
            ghcr.io/schaka/janitorr:native-${{ steps.branch_name.outputs.value }}
            ${{ (startsWith(github.ref, 'refs/tags/v') && 'ghcr.io/schaka/janitorr:native-stable') || '' }}
          sources: |
            ghcr.io/schaka/janitorr:native-amd64-${{ steps.branch_name.outputs.value }}
            ghcr.io/schaka/janitorr:native-arm64-${{ steps.branch_name.outputs.value }}